This document lists tests which we can expect to continue to fail for valid reasons.

======================================================================
ERROR: testIdentify (Products.CMFPlone.tests.testUserFolderBasics.TestUserFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\zope-pas\Products\CMFPlone\tests\testUserFolderBasics.py", line 59, in testIdentify
    name, password = self.uf.identify(self.basic)
AttributeError: identify

# The identify attribute is used only for HTTP basic authentication, and PAS
# is not going to implement a basic auth plugin. Any users created above the
# Plone instance (for example 'admin') will still have basic auth available
# to them inside Plone (for example, to view the ZMI) because identify will
# be called correctly on the user folder where they are defined.

======================================================================
ERROR: testAuthenticate (Products.CMFPlone.tests.testUserFolderBasics.TestUserFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\zope-pas\Products\CMFPlone\tests\testUserFolderBasics.py", line 99, in testAuthenticate
    self.failUnless(user.authenticate('secret', self.app.REQUEST))
  File "C:\Program Files\Zope-2.7.4-0\lib\python\AccessControl\User.py", line 121, in authenticate
    passwrd=self._getPassword()
  File "C:\Program Files\Zope-2.7.4-0\lib\python\AccessControl\User.py", line 77, in _getPassword
    raise NotImplementedError
NotImplementedError

# As above, basic auth is not implemented.

======================================================================
ERROR: testValidateWithoutRoles (Products.CMFPlone.tests.testUserFolderBasics.TestUserFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\zope-pas\Products\CMFPlone\tests\testUserFolderBasics.py", line 113, in testValidateWithoutRoles
    self.assertEqual(user.getUserName(), default_user)
AttributeError: 'NoneType' object has no attribute 'getUserName'

# Since Basic Auth is not implemented, the validate() method is returning None
# and not a valid user object, and calling getUserName() on None produces an error.

======================================================================
FAIL: testValidate (Products.CMFPlone.tests.testUserFolderBasics.TestUserFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\zope-pas\Products\CMFPlone\tests\testUserFolderBasics.py", line 103, in testValidate
    self.failIfEqual(user, None)
  File "C:\Python23\lib\unittest.py", line 310, in failIfEqual
    raise self.failureException, \
AssertionError: None == None

# Since Basic Auth is not implemented, the validate() method is returning None
# and not a valid user object, and None == None, so the test fails.


